test:
  image: python:3-alpine3.6
  script:
    - apk --no-cache install g++
    - pip install -r requirements.txt
    - pip install unittest2
    - python3 -m unittest discover

pages:
  image: $CI_REGISTRY/docker/python-sphinx
  script:
    - /build.sh
  artifacts:
    paths:
      - public
  only:
    - master
