test:
  image: $CI_REGISTRY/docker/python-pytest
  script:
    - printenv
    - /build.sh

pages:
  image: $CI_REGISTRY/docker/python-sphinx
  script:
    - /build.sh
  artifacts:
    paths:
      - public
  only:
    - master
