test:
  image: python:3-alpine3.6
  script:
    - apk --no-cache add g++
    - pip install -r requirements.txt
    - pip install unittest2 pytest pytest-cov
    - py.test --cov=modbusreader

pages:
  image: $CI_REGISTRY/docker/python-sphinx
  script:
    - /build.sh
  artifacts:
    paths:
      - public
  only:
    - master
